
target 'SuiYiWan' do
pod 'AFNetworking', '~> 3.1.0'
pod 'MJExtension', '~> 3.0.13'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'SDWebImage', '~> 3.7.6'
pod 'DACircularProgress', '~> 2.3.1'
pod 'MJRefresh', '~> 3.1.12'
end
